SELECT *  FROM RAW_DATA.SHAREPOINT_SIMPLE.DOC_METADATA_RAW;

SELECT *  FROM RAW_DATA.SHAREPOINT_SIMPLE.DOC_METADATA_RAW;
CREATE OR REPLACE DYNAMIC TABLE DATABASE.SCHEMA.DOCS_METADATA_DT
    TARGET_LAG = '1 hour'
    WAREHOUSE = MYWH
AS
SELECT
    PARSE_JSON(METADATA):"Approved"::STRING AS APPROVED,
    PARSE_JSON(METADATA):"AuthorLookupId"::STRING AS AUTHOR_LOOKUP_ID,
    PARSE_JSON(METADATA):"CHANGE_TYPE"::STRING AS CHANGE_TYPE,
    PARSE_JSON(METADATA):"CREATED_BY_EMAIL"::STRING AS CREATED_BY_EMAIL,
    PARSE_JSON(METADATA):"CREATED_BY_NAME"::STRING AS CREATED_BY_NAME,
    PARSE_JSON(METADATA):"ContentType"::STRING AS CONTENT_TYPE,
    PARSE_JSON(METADATA):"Created"::TIMESTAMP AS CREATED,
    PARSE_JSON(METADATA):"DRIVE_NAME"::STRING AS DRIVE_NAME,
    PARSE_JSON(METADATA):"DealID"::NUMBER AS DEAL_ID,
    PARSE_JSON(METADATA):"DocIcon"::STRING AS DOC_ICON,
    PARSE_JSON(METADATA):"FILENAME"::STRING AS FILENAME,
    PARSE_JSON(METADATA):"FILE_ID"::STRING AS FILE_ID,
    PARSE_JSON(METADATA):"FILE_SIZE"::NUMBER AS FILE_SIZE,
    PARSE_JSON(METADATA):"FILE_URL"::STRING AS FILE_URL,
    PARSE_JSON(METADATA):"FileLeafRef"::STRING AS FILE_LEAF_REF,
    PARSE_JSON(METADATA):"ITEM_TYPE"::STRING AS ITEM_TYPE,
    PARSE_JSON(METADATA):"MODIFIED_BY_EMAIL"::STRING AS MODIFIED_BY_EMAIL,
    PARSE_JSON(METADATA):"MODIFIED_BY_NAME"::STRING AS MODIFIED_BY_NAME,
    PARSE_JSON(METADATA):"Modified"::TIMESTAMP AS MODIFIED,
    PARSE_JSON(METADATA):"ProjectName"::STRING AS PROJECT_NAME,
    PARSE_JSON(METADATA):"SHAREPOINT_PATH"::STRING AS SHAREPOINT_PATH,
    PARSE_JSON(METADATA):"SITE_URL"::STRING AS SITE_URL,
    PARSE_JSON(METADATA):"_UIVersionString"::STRING AS UI_VERSION_STRING,
    PARSE_JSON(METADATA):"id"::STRING AS ID
FROM RAW_DATA.SHAREPOINT_SIMPLE.DOC_METADATA_RAW
QUALIFY ROW_NUMBER() OVER (PARTITION BY FILE_ID ORDER BY MODIFIED DESC) = 1;